version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  test_and_linting:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14.16.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Run TypeScript linting
          command: yarn lint:tsc
      - run:
          name: Run ESLint linting
          command: yarn lint:eslint
      - run:
          name: Run Stylelint linting
          command: yarn lint:css
      - run:
          name: Run tests
          command: yarn test
  stage:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: $HEROKU_STAGING_APP_NAME
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: $HEROKU_PRODUCTION_APP_NAME

workflows:
  stage_test_deploy:
    jobs:
      - test_and_linting
      - stage:
          requires:
            - test_and_linting
      - hold:
          type: approval
          requires:
            - stage
      - deploy:
          requires:
            - hold
